### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by Grienauer** [krabina/Datencockpit#11]
Wird ein Docker Container auch zur Verfügung gestellt werden?

**Comment by krabina** [comment]
Ist derzeit nicht geplant. Habe mal 2 Stunden versucht, mit mit Docker zu beschäftigen und MediaWiki zum Laufen zu bringen und bin gescheitert :-(
Aber wenn jemand mit Docker-Know-How ausghelfen mag, ich stelle gerne MediaWiki-Know-how zur Verfügung...

**Comment by soudis** [comment]
Sollte laufen, mit docker-compose halt:

https://github.com/soudis/datencockpit-docker

**Comment by soudis** [comment]
Wenn du willst, kannst du das einfach bei den Installationsvarianten verlinken

**Comment by krabina** [comment]
Schon erledigt! Vielen Dank!
