### ISSUE TITLE
First letter bei Organisation

### ISSUE THREAD

**Issue by selecta-ufuk** [krabina/Datencockpit#12]
Nur eine Kleinigkeit! Wir haben einen kleingeschriebenen Namen. 
Das wiki zeigt aber den ersten Buchstaben bei Stammdaten immer grossgeschrieben an.
Vielleicht könntet ihr das fixen oder mir schreiben wie ich das ändern kann !
Thx 
p.s. Tolle Arbeit!

**Comment by krabina** [comment]
https://www.mediawiki.org/wiki/Manual:$wgCapitalLinks 
hab ich aber noch nie versucht...
