### ISSUE TITLE
Multibyte files scrambled

### ISSUE THREAD

**Issue by kghbln** [krabina/Datencockpit#13]
After downloading and extracting the files the names containing umlauts are scrambled like e.g. "Bearbeiten-Men.png"

**Comment by kghbln** [comment]
Moreover "Datencockpit.png" and "Datemcockpit.png" appear to be dupes.

**Comment by krabina** [comment]
Keine Ahnung, warum. Hat bisher noch niemand beanstandet. 
Das doppelte File lösche ich raus, das Umlaut-Problem müssen wir weiterverfolgen.

**Comment by kghbln** [comment]
Verschiebe doch einfach die Datei nach "Bearbeiten-Menue.png" und ändere die Einbindungen entsprechend. So kannst Du das Problem umgehen. Gleiches für die beiden anderen betroffenene Dateien. Zip zerhackt regelmäßig Dateien.

**Comment by kghbln** [comment]
> Hat bisher noch niemand beanstandet.

Doch. Siehe https://github.com/krabina/Datencockpit/issues/15

**Comment by jfiala** [comment]
Das Problem besteht nur unter Windows, unter Unix ist alles OK - siehe #15...

**Comment by jfiala** [comment]
Wenn man auf http://www.datencockpit.at/Datencockpit geht, dann werden auch die Dateien mit Umlaut richtig angezeigt (ich vermute es läuft unter Unix).
Wenn man das Datencockpit lokal auf Windows deployed und darauf zugreift, werden die Grafiken mit Umlauten im Dateinamen nicht angezeigt.

**Comment by kghbln** [comment]
Ah, jetzt bin ich wieder auf Kurs. Danke für den Hinweis.

Nein, das ist wohl ein generelles Problem. Ich nutze ausschließlich Linux und dort habe ich es auch. Ich tippe auf das komprimieren mit zip. Bei diesem Vorgang werden die Umlaute zerhackt.

**Comment by krabina** [comment]
in [V 1.0](https://github.com/krabina/Datencockpit/releases/tag/1.0) behoben.

**Comment by kghbln** [comment]
> in V 1.0 behoben.

Bin mir nicht sicher. Wenn ich https://github.com/krabina/Datencockpit/blob/1.0/wiki/Icons.zip entpacke, dann sind die Dateien immer noch "zerhackt", d.h. ich muß sie vor dem Hochladen umbenennen. 

Ich meine mich zu erinnern, daß zip auf Windows das Problem automatisch verursacht. :(
