### ISSUE TITLE
Beispiel DB-User anlegen ergänzen bei INSTALLATION.md

### ISSUE THREAD

**Issue by jfiala** [krabina/Datencockpit#14]
Installation.md:
* Legen Sie einen DB-User an,...

Gut wäre ein Beispiel bzw. die Info welche Rechte genau benötigt werden.
```
CREATE USER 'kdz_datencockpit'@'localhost' IDENTIFIED BY '<kennwort>';
use kdz_datencockpit;

GRANT CREATE, ALTER, SELECT, INSERT, UPDATE, DELETE, DROP ON * TO 'kdz_datencockpit'@'localhost';
GRANT CREATE TEMPORARY TABLES  ON * TO 'kdz_datencockpit'@'localhost';
flush privileges;
```

Das wären die benötigten Rechte für den DB-User.
Es könnte natürlich auch ein eigenes create_user.sql bereitgestellt werden.

**Comment by krabina** [comment]
MediaWiki schlägt sogar vor:
`GRANT ALL PRIVILEGES ON * TO 'kdz_datencockpit'@'localhost' IDENTIFIED BY 'password';`
siehe
https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki#MariaDB/MySQL

**Comment by jfiala** [comment]
Stimmt, aber FLUSH PRIVILEGES & etwas Fine-Tuning hilft den unerfahreneren Usern.
Noch besser wäre CREATE und DROP an einen User für die maintenance zu assignen, beim Daten bearbeiten wird es wohl selten gebraucht. Ist aber dann wohl eher Thema für MediaWiki.
