### ISSUE TITLE
Windows Fehler beim Erstellen des Vorschaubildes: Datei fehlt

### ISSUE THREAD

**Issue by jfiala** [krabina/Datencockpit#15]
Unter Windows werden die Grafiken mit Umlauten im Dateinamen nicht angezeigt, es wird eine Fehlermeldung angezeigt:
Fehler beim Erstellen des Vorschaubildes: Datei fehlt

Beispiele: Folgenabschätzung, Lösch-/Änderungsantrag

SOLL: Grafik soll angezeigt werden - entweder umbenennen oder für richtige Auflösung auch unter Windows sorgen.

In der Installation steht:
Wegen mangelhafter PHP-Implementierung unter Windows wird von Windows-Servern abgeraten! Ein Linux-Server ist rasch installiert.
Ich konnte keine Fehler feststellen, außer den o.a. Grafiken.

**Comment by krabina** [comment]
da bin ich leider etwas ratlos und freue mich über Hinweise, was da falsch läuft...

**Comment by kghbln** [comment]
Widergänger von https://github.com/krabina/Datencockpit/issues/13 - Einfach im Orginal die Dateien verschieben, Verwendungen anpassen und alles mit der nächsten Version veröffentlichen.

**Comment by jfiala** [comment]
Noch besser wäre den Fehler zu beheben oder als Quick-Fix Dateien umbenennen ohne Umlaute :), betrifft ja nur die beiden Dateien mit Umlauten im Dateinamen wg. UTF-8.

**Comment by jfiala** [comment]
Bei mir im TAR ist der Umlaut noch korrekt:
datencockpitV0-2.tar\datencockpit\images\thumb\1\19\Folgenabschätzung.png
Das Problem dürfte beim Einlesen entstehen, dort wird anscheinend die Dateinamen als UTF-8 gesucht und dann nicht gefunden weil Windows die Dateinamen nicht in UTF-8 interpretiert.

Gesucht wird: Folgenabsch%C3%A4tzung
=> ist url-dekodiert dann Folgenabschätzung in UTF-8 (mit zwei Bytes für Umlaut)
=> diese Datei wird dann nicht gefunden da im Filesystem Folgenabschätzung mit "ä" in Windows 1252 vorliegt. Bei Unix mit UTF-8 als Charset funktioniert es da dort der Dateiname mit UTF-8 gefunden werden kann.

```
<div class="MediaTransformError" style="width: 40px; height: 40px; display:inline-block;">Fehler beim Erstellen des Vorschaubildes: Datei fehlt</div> <a href="/index.php?title=Folgenabsch%C3%A4tzung" title="Folgenabschätzung">Folgenabschätzung</a>
```

**Comment by krabina** [comment]
in [V 1.0](https://github.com/krabina/Datencockpit/releases/tag/1.0) behoben.
