### ISSUE TITLE
Sensible Daten / besondere Kategorien

### ISSUE THREAD

**Issue by jfiala** [krabina/Datencockpit#16]
Im Verfahrensverzeichnis gibt es die Spalte "sensible Daten".
Wäre nach der DSG-VO nicht "besondere Kategorien" der richtigere Begriff?

**Comment by krabina** [comment]
Das stimmt grundsätzlich. Art. 9 kennt den Begriff der "sensiblen Daten" nicht. Es gibt aber bereits einen Hinweis im Formular für die Verhahren (im "?"-Info-Feld). 

Ich habe nun diesen Hinweis auch in der Vorlage eingefügt, damit er auch bei der Anzeige des Verfahrensverzeichnisses aufscheint:
http://www.datencockpit.at/index.php?title=Vorlage%3AVerfahren&type=revision&diff=3235&oldid=3216

Die Datenschutzberhörde verwendet diesen Begriff auch, siehe Erläuterung zu Artikel 30 (ganz unten auf der Seite)
http://www.datencockpit.at/DSGVO:Artikel_30._Verzeichnis_von_Verarbeitungst%C3%A4tigkeiten

Aus zwei Gründen möchte ich das nicht ändern.
1. halte ich den Begriff für die User für verständlicher als "besondere Kategorien personenbezogener Daten" und auch kürzer und damit einfacher handhabbar
2. is es im Wiki nicht nur eine Bezeichnung, sondern ein Datenelement. Eine Änderung müsste daher an sehr vielen Stellen durchgezogen werden.

**Comment by jfiala** [comment]
finde ich OK, der Begriff sensible Daten stammt aus § 4 Z 2 DSG 2000 (https://www.ris.bka.gv.at/Dokument.wxe?Abfrage=Bundesnormen&Dokumentnummer=NOR40113702) ist aber wohl allgemein verständlicher.
