### ISSUE TITLE
Tippfehler

### ISSUE THREAD

**Issue by riess82** [krabina/Datencockpit#17]
Tippfehler bei "Letze Änderung", zum Beispiel:
"Letze Änderung am 17. 4. 2018 von Admin."

da fehlt ein t

**Comment by krabina** [comment]
Danke, habs in unserer öffentlichen Installation geändert. 
http://www.datencockpit.at/index.php?title=Verfahrensverzeichnis&type=revision&diff=3234&oldid=3218
In bestehenden kann man das einfach selbst nachholen.
