### ISSUE TITLE
Skriptpath went missing

### ISSUE THREAD

**Issue by kghbln** [krabina/Datencockpit#18]
`www.datencockpit.at` was setup without a script path which is a non standard setup. So if somebody follows recommendations and sets up a wiki with a script path some links will not work, e.g. on "Fomular:Benutzer" there are even hard coded links with `www.datencockpit.at`:

`[http://www.datencockpit.at/index.php?title=Spezial:Anmelden&type=signup Benutzerkonto anlegen]`

Could you try if this works on `www.datencockpit.at` and change links respectively if it does?:

`[{{SERVER}}{{SCRIPTPATH}}/index.php?title=Special:Login&type=signup Benutzerkonto anlegen]`

**Comment by krabina** [comment]
danke!
http://www.datencockpit.at/index.php?title=Formular%3ABenutzer&type=revision&diff=3236&oldid=3125

**Comment by krabina** [comment]
danke!
http://www.datencockpit.at/index.php?title=Formular%3ABenutzer&type=revision&diff=3236&oldid=3125

**Comment by kghbln** [comment]
Super, das klappt dann auch mit Scriptpath. Man müßte nur noch schauen, ob andere Stellen betroffen sind.

**Comment by krabina** [comment]
Meines Wissens nach gibt es das sonst nirgendwo.

**Comment by kghbln** [comment]
Na dann ist wohl alles tutti. :)

**Comment by krabina** [comment]
in [V 1.0](https://github.com/krabina/Datencockpit/releases/tag/1.0) behoben.
