### ISSUE TITLE
Verantwortliche werden im Verfahrensverzeichnis nicht korrekt erkannt

### ISSUE THREAD

**Issue by maschinengeist** [krabina/Datencockpit#2]
Im Verfahrensverzeichnis wird der Verantwortliche nicht korrekt ausgewiesen. Das Datencockpit meldet "Sie haben keine Verantworliche BenutzerInnen definiert!"

Die Seite /Verfahrensverzeichnis muss wie folgt angepasst werden:

```
=== Verantwortliche ===
{{#ask: [[Kategorie:BenutzerInnen]] [[Funktion::Verantwortliche/r]]
|mainlabel=BenutzerIn
|?Abteilung
|?Vorname
|?Nachname
|?Telefon
|?E-Mail
|format=template
|template=Benutzerdaten
|link=none
|default=<div class="alert alert-danger">[[Image:Fail.png|30px|left|link=BenutzerInnen]] Sie haben keine Verantworliche [[BenutzerInnen]] definiert!</div>
}}
```
Die Seite /Verzeichnis_der_Verarbeitungst%C3%A4tigkeiten muss wie folgt angepasst werden:

```
=== Verantwortliche ===
{{#ask: [[Kategorie:BenutzerInnen]] [[Funktion::Verantwortliche/r]]
|mainlabel=BenutzerIn
|?Abteilung
|?Vorname
|?Nachname
|?Telefon
|?E-Mail
|format=template
|template=Benutzerdaten
|link=none
|default=<div class="alert alert-danger">[[Image:Fail.png|30px|left|link=BenutzerInnen]] Sie haben keine Verantworliche [[BenutzerInnen]] definiert!</div>
}}
```

Das Template bzw. die Seite /Vorlage:Benutzerdaten sollte wie folgt angepasst werden:

```
<noinclude>Vorlage für Anzeige von Benutzerdaten
<pre>
{{Benutzerdaten}}
</pre>
[[Kategorie:Vorlagen]]
</noinclude><includeonly>
 {{{3}}} {{{4}}} 
 {{{5}}}
 {{{6}}}</includeonly>
```

Schöne Grüße,

Stefan

**Comment by krabina** [comment]
Danke, das ist leider korrekt. Und es betrifft auch weitere Vorlagen:
http://www.datencockpit.at/index.php?title=Vorlage%3AVerletzung&type=revision&diff=3177&oldid=2640
http://www.datencockpit.at/index.php?title=Vorlage%3AFolgen&type=revision&diff=3178&oldid=3026
http://www.datencockpit.at/index.php?title=Vorlage%3ABerichtigung&type=revision&diff=3179&oldid=2636
http://www.datencockpit.at/index.php?title=Vorlage%3AAuskunft&type=revision&diff=3180&oldid=2653

**Comment by krabina** [comment]
In V 0.2 behoben

**Comment by ZoXx** [comment]
ist immer noch als Bug vorhanden?
