### ISSUE TITLE
Daten werden nicht upgedated

### ISSUE THREAD

**Issue by segro21** [krabina/Datencockpit#21]
Hallo zusammen,
super projekt! Installation ging gut, aber wenn ich z.B. eine Organisation oder VVT erstelle, wird das nicht in den entsprechenden Bereichen angezeigt, insbesondere bei der Checkliste. Bei der Suche taucht es dann wieder auf.
muss da erst ein cronjob laufen? ich bin als admin eingeloggt.

**Comment by Zabien** [comment]
MediaWiki hat ja die [Job Queue][https://www.mediawiki.org/wiki/Manual:Job_queue], da kann das mit den semantischen Ausgaben ein bisschen dauern. Wenn ein einfaches Neuladen der Seite (>Mehr > neu laden bzw. >More >Refresh) im Wiki nichts hilft, zum Beschleunigen das [PHP-Skript runjobs.php][https://www.mediawiki.org/wiki/Manual:RunJobs.php] laufen lassen, damit ist es meist erledigt. Dafür am besten einen Cronjob einrichten.

**Comment by segro21** [comment]
wow, support um die Uhrzeit... Danke! ... neu laden hat geholfen. perfekt!
