### ISSUE TITLE
no upload

### ISSUE THREAD

**Issue by segro21** [krabina/Datencockpit#22]
hi,
wenn ich Dokumente hochladen möchte, erscheint nur eine weiße box (overlay) und im apache log sehe ich noch den aufruf der fancybox.. 
muss da noch mehr eingestellt werden in LocalSettings.php? welche berechtiungen auf das imges verzeichnis?

**Comment by krabina** [comment]
https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads
