### ISSUE TITLE
Installation in bestehendes Wiki: Fehlende Inhalte und Skininstallation

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [krabina/Datencockpit#25]
Hallo Zusammen!
Danke für das Datencockpit! 
Ich wollte es in ein bestehendes Wiki installieren will, musste dabei aber feststellen, dass in den Exportdateien einige Inhalte fehlen:
z.B: folgende Seiten
* Die Startseite "Datencockpit"
* "DSGVO" und "Datenschutzgrundverordnung"
* "Datenschutz-Anpassungsgesetz"
* "Informationspflichten"
* "Folgenabschätzung"
* "Auskunftsersuchen"
* "Löschantrag"
* "Datenschutzverletzung"

Außerdem ist die Anleitung bezüglich Installation des Skins etwas mager. Die entsprechenden Dateien gehören vermutlich in ein Verzeichnis "skins/kdz" (o.ä.)? Und dann muss der Skin mit wfLoadSkin( ... ) geladen werden?

Viele Grüße
Hermann

**Comment by krabina** [comment]
Danke für den Hinweis. Stimmt, einige der Seite im Main-Namespace haben gefehlt.
in [V 1.0](https://github.com/krabina/Datencockpit/releases/tag/1.0) behoben.

Habe zusätzlich noch ein extra XML-File mit diesen Seiten erstellt, falls Bedarf besteht:
[Datencockpit-Fehlende-Seiten.zip](https://github.com/krabina/Datencockpit/files/2039652/Datencockpit-Fehlende-Seiten.zip)
