### ISSUE TITLE
Benutzer loeschen

### ISSUE THREAD

**Issue by Ukae6que** [krabina/Datencockpit#26]
Hallo,
gibt eine Moeglichkeit, einen bestehenden BenutzerIn zu loeschen?
Danke

Carsten

**Comment by WinMacDroid** [comment]
Ja gibt es, dafür musst du einen Benutzer über das Benutzerverzeichnis auswählen und dann oben rechts auf das Menü klicken (die drei kleinen Punkte). Im Dropdownmenü "Löschen" auswählen und Bestätigen.

**Comment by Ukae6que** [comment]
Hallo,

wenn ich den Benutzer aufrufe und dann die drei Punkte anklicke, habe ich keine Option zum Loeschen... (s. Screenshot).

Viele Gruesse

Carsten

--
system-admin.info
IT-Systemberatung, Infrastruktur, Netze
Carsten John
Cruesemannallee 13
28213 Bremen 
 
-----Original message-----

**Comment by krabina** [comment]
Dann hat dein User nicht die Rechte dazu. Kannst du dir auf der Seite Spezial:Gruppenrechte ansehen. Der user, der Seiten löschen will, braucht das "delete"-Recht. 
Als Admin-User funktioniert das. Dieser User kann auch anderen Usern Rechte via Spezial:Benutzerrechte erteilen.

**Comment by Ukae6que** [comment]
Danke, mein Fehler....



--
system-admin.info
IT-Systemberatung, Infrastruktur, Netze
Carsten John
Cruesemannallee 13
28213 Bremen 
 
-----Original message-----
