### ISSUE TITLE
Fehler beim Erstellen des Vorschaubildes

### ISSUE THREAD

**Issue by HassbergKliniken** [krabina/Datencockpit#27]
Es wird folgender Fehler angezeigt:

`Fehler beim Erstellen des Vorschaubildes: /bin/bash: /usr/bin/convert: No such file or directory

Error code: 127`

ImageMagick wurde mittels `apt-get install imagemagick imagemagick-doc` installiert.
convert ist auch vorhanden:
```
root@datencockpit:/# locate /usr/bin/convert
/usr/bin/convert
/usr/bin/convert-im6
```

**Comment by krabina** [comment]
ist das auf einem Windows-Server?

Vermutlich ähnlich wie [15](https://github.com/krabina/Datencockpit/issues/15) - dort waren es nur die beiden Files mit Umlauten, die das Problem verursacht haben. Es gibt nun die beiden Files "Folgenabschätzung.png" als "Folgenabschaetzung.png" und "Löschantrag.png" als "Loeschantrag.png". Die mit Umlaut könnte man löschen.

**Comment by HassbergKliniken** [comment]
Hallo,

ich verstehe die Frage nicht ;)
Nein, selbstverständlich eine Ubuntu 16.04 in 64Bit.

Ich habe in der LocalSettings.php noch die Variable `$wgUseImageResize  = true;` eingefügt.
Server mittels `apt-get update` und `apt-get dist-upgrade` auf den neusten Stand gebracht und durchgebootet. Fehler erscheint nicht mehr!

**Comment by krabina** [comment]
interessant, true wäre ohnehin der default wert. Kenne mich (wie man merkt) mit imagemagick etc. nicht besonders gut aus. Schön, dass es jetzt klappt!
