### ISSUE TITLE
Feature: Datei up/download Auftragsverarbeiter

### ISSUE THREAD

**Issue by HassbergKliniken** [krabina/Datencockpit#29]
Hallo,

wäre es möglich bei den jeweiligen "Auftragsverarbeiter" ein Datei up/download einzurichten?
Hintergrund: wir digitalisieren unsere ADVs und würden sie gerne dort einpflegen.

Besten Dank!

**Comment by krabina** [comment]
Das gibts doch schon. Im Formular bei Auftragsverarbeiter gibt es das Feld Dokument, dort kann man ein File uploaden.
![grafik](https://user-images.githubusercontent.com/4318745/40656962-77f40f00-6346-11e8-881d-e68c40cb15e5.png)
