### ISSUE TITLE
Probleme bei der Installation

### ISSUE THREAD

**Issue by tomate61** [krabina/Datencockpit#36]
Hallo,

ich versuche seit geraumer Zeit das Datencockpit auf Ubuntu 16.04 LTS Desptop zum laufen zu kriegen.
Das ganze läuft unter LAMP.

Habe mich an folgende Anleitung gehalten: https://github.com/krabina/Datencockpit/blob/master/webserver/INSTALLATION.md

Und das ist das Ergebnis:

![image](https://user-images.githubusercontent.com/41470899/43455955-e0522e68-94c1-11e8-823c-1ad82a0e8155.png)

Wäre schön, wenn jemand dazu einen Tipp hätte.
Danke im Voraus.

**Comment by klausmad** [comment]
Hallo,

prüfe mal die Rechte / Besitzer / Gruppen von  /var/www , die Ordner sollten alle www-data  www-data sein.
Wenn du als root entpackt hast, hat der apache keinen Zugriff auf die CSS Dateien die die Dartsellung formatieren würden. Bei mir ist es ein lokaler Server Netzwerk intern, daher habe ich alle Ordner auf 0755 gesetzt. Wenn der Server im Internet ist, sollte man aber genau prüfen welche Ordner man freigibt.

Mehr zu chmod: https://wiki.ubuntuusers.de/chmod/

und zu chown: https://wiki.ubuntuusers.de/chown/

oder mit WINSCP, das dauert aber oft länger....

LG Klaus

**Comment by tomate61** [comment]
Hallo,
auch ich habe es lokal laufen.
Habe die Änderungen durchgeführt, leider ohne Ergebnis.
Kann es evtl auch an der Datenbank leigen?

**Comment by jifflaender** [comment]
Moin,

klingt evtl. auch nach inkonsistenter LocalSettings.php.
Bei mir läuft das Datencockpit in einem Unterverzeichnis von /var/www/html. Die Einstellungen in der LocalSettings.php sehen dann im entsprechenden Abschnitt so aus:
_____________________________________

$wgSitename = "Datencockpit";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/Unterverzeichnis";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://www.meine-domain.de";
#$wgScriptExtension = ".php";
$wgArticlePath = "/Unterverzeichnis/index.php/$1";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;
____________________________________________

Bei mir reichte übrigens ein "chown" auf www-data:www-data. Ein "chmod" war nicht notwendig.

Beste Grüße und viel Erfolg

**Comment by tomate61** [comment]
Danke, für die Hilfe nun funktioniert alles.

**Comment by Ogolar** [comment]
Merci, hat mir auch geholfen. Hatte was übersehen;

**Comment by krabina** [comment]
super, danke an alle im Thread für den Support!
