### ISSUE TITLE
Bild Fehler

### ISSUE THREAD

**Issue by DieKuhMachtMuhh** [krabina/Datencockpit#38]
Guten Tag, 

ich habe die Software heute endeckt und wollte sie einmal ausprobieren, dort sind mehr kleinere Fehler aufgefallen, ich weiß nicht ob sie meinerseits kommen.

Wenn ich auf den Menüpunkt Stammdaten -> Organisation kommt bei mir der Fehler das er das Vorschaubild nicht laden konnte und unter "Letzte Änderung" erscheint der Error code: 127
Bild: http://prntscr.com/kpdxb3 

Wenn ich auf die Profile gehe kommt dort der Gleiche Fehler bei dem Bild für die Folgenabschätzung und Löschanträge

**Comment by jifflaender** [comment]
Hallo,
wenn /usr/bin/convert nicht vorhanden ist: Installation ImageMagick mit "sudo apt-get install imagemagick imagemagick-doc"
des weiteren siehe auch Post https://github.com/krabina/Datencockpit/issues/27
Beste Grüße

**Comment by DieKuhMachtMuhh** [comment]
Ich nutze einen normalen Webserver für die Anwendung, hatte ich dann doch leider vergessen zu erwähnen. 
So habe ich keine Möglichkeit das zu beheben?

**Comment by jifflaender** [comment]
Hallo,
die Voraussetzungen sind hier aufgeführt: 
https://www.mediawiki.org/wiki/Manual:Installation_requirements

"_Ich nutze einen normalen Webserver_" übersetze ich jetzt einmal mit: "I_ch habe keinen root-access auf dem Server_". Denn "normale" Webserver nutzen wir alle...
Es ist wie es ist: wenn die Voraussetzungen nicht geschaffen werden können, funktioniert es nicht so wie gewünscht...

**Comment by krabina** [comment]
ja, stimmt. Den Webhoster bitten, imagemagick zu installieren, sonst klappt es nicht mit den Bildern.
