### ISSUE TITLE
Falsche Url zum Anlegen von Benutzern

### ISSUE THREAD

**Issue by maschinengeist** [krabina/Datencockpit#4]
Auf der Seite /BenutzerInnen wird auf datencockpit.at anstatt auf die lokale Installation verwiesen.

Der Text solle wie folgt angepasst werden:

`[[Spezial:Benutzer|BenutzerInnen]] im Datencockpit können von Administratoren über die Seite [{{fullurl:Spezial:Anmelden|type=signup}} Benutzerkonto anlegen] hinzugefügt werden.`

**Comment by Zabien** [comment]
Stimmt, danke für den Input! Ist geändert!

**Comment by krabina** [comment]
Danke!

**Comment by krabina** [comment]
on second thought: werde das erst closen, wenn die Version 0.2 draussen ist. So ist es für diejenigensichtbarer, die die V0.1 installiert haben.

**Comment by krabina** [comment]
In V 0.2 behoben
