### ISSUE TITLE
Auftragsverarbeiter 2 neue Felder

### ISSUE THREAD

**Issue by ZoXx** [krabina/Datencockpit#42]
Hallo zusammen,
ich habe es relativ lange probiert, bekomme es aber nicht sauber hin.

Ich hätte gerne 2 weitere Felder beim erstellen des "Auftragsverarbeiter".
1. AV Datum => hier soll das Datum eingetragen werden können
2. AV => hier soll ausgewählt werden können: ja, nein, angefragt

Die Attribute habe ich schon angelegt, jedoch stehe ich vor dem Problem:
Wie passe ich das vorhandene Formular an?
Ich kann zwar ein neues erstellen, dass sieht Formatierungsmäßig aber nicht pralle aus. Wenn man das dann bearbeitet, steht das neue Formular nur im Reiter "Weitere Informationen" und auch nur als Quelltext. 

Kann mir hier wer helfen?

**Comment by ZoXx** [comment]
@jifflaender kannst du hier vielleicht auch weiterhelfen?

**Comment by jifflaender** [comment]
Moin @ZoXx ,

z. B. Datum:
Formular bearbeiten (**...\index.php/Formular:Auftragsverarbeiter** und dann auf das Stiftsymbol oben rechts im Menü). An gewünschter Stelle einfügen (natürlich mit Deinen Namenskonventionen bei den Attributen):

```
|-
| Datum AV:
|{{#info:Datum AV}}
|{{{field|Datum|input type=datepicker|show week numbers|week start=1|highlight days of week=0|date format=dd.mm.yy}}}

```
ähnlich beim Status AV:
```
|-
| Status AV:
|{{#info:Status AV}}
|{{{field|Status|input type=dropdown|class=form-control}}}
```

**Comment by ZoXx** [comment]
GRandios! Vielen vielen Dank dafür! Ich habe es seit 2 Tagen versucht, so langsam verstehe ich den Grudnaufbau des Wikis nun. 

Die Attribute lege ich dann über folgende Seite an?
/index.php?title=Spezial:Attribut_erstellen

Bei AV Status soll z.B. gefragt sein: vorhanden, nicht vorhanden, angefragt

**Comment by jifflaender** [comment]
Moin @ZoXx ,

ja, das ist die richtige Seite (sagtest Du nicht, Du hättest die Attribute bereits erstellt?).

Für das Datum ist der Typ "Datum".
Für den Status ist der Typ "Text" mit dem Inhalt
```
Dies ist eine Eigenschaft des Typs [[Datentyp::Text]].

Die möglichen Werte für diese Eigenschaft sind:

* [[Erlaubt Wert::1 - vorhanden]]
* [[Erlaubt Wert::2 - nicht vorhanden]]
* [[Erlaubt Wert::3 - angefragt]]

[[Kategorie:Attribute]]
```

siehe dazu auch Beispiele: 

- .../index.php/Spezial:Attribute
- .../index.php/Attribut:Status_des_Antrags
- .../index.php?title=Attribut:Status_des_Antrags&action=edit

**Comment by ZoXx** [comment]
Hallo @jifflaender ,
jouw genau, allerdings blicke ich das ganze noch nicht 100%. 
Die Verlinkung ist noch nicht drin.

1. Ich lege das Attribut unter: /index.php?title=Spezial:Attribut_erstellen an. Das Attribut nenne ich z.B. `StatusAV`
Wenn es angelegt ist, bearbeite ich die folgende Seite mit:
```
Dies ist eine Eigenschaft des Typs [[Datentyp::Text]].
Die möglichen Werte für diese Eigenschaft sind:
* [[Erlaubt Wert::1 - vorhanden]]
* [[Erlaubt Wert::2 - nicht vorhanden]]
* [[Erlaubt Wert::3 - angefragt]]
[[Kategorie:Attribute]]
```
nun gehe ich in das Formular via /index.php?title=Formular:Auftragsverarbeiter und füge den Code ein:
```
| Status AV:
|{{#info:Status des AV. Sie können hier zwischen: vorhanden, nicht vorhanden, angefragt wählen.}}
|{{{field|StatusAV|input type=dropdown|class=form-control}}}
```

Das Feld erkennt anhand des `field|StatusAV|` das es dieses Attribut mit den 3 eingestellten Werten sein muss? 

In dem Formular wurden ja die beiden Felder oben eingefügt. Sobald der Auftragsverarbeiter angelegt ist, erscheint ja die Übersicht zu diesem. Dort fehlen die beiden Informationen noch. Wie komme ich da denn ran?

**Comment by krabina** [comment]
Du brauchst noche eine Vorlage. Das Forular übergibt die Werte aus der Eingabe nur an die Vorlage. In dieser wird die resultierende Seite formatiert und dort werden auch die Werte gesetzt. 
https://www.semantic-mediawiki.org/wiki/Help:User_manual
Du kannst übrigens eine Attributseite wie eine normale Wiki-Seite erstellen. Spezial:Attribut_erstellen muss man nicht verwenden.

**Comment by jifflaender** [comment]
Moin @ZoXx ,

...indem Du die Vorlage bearbeitest

- .../index.php/Vorlage:Auftragsverarbeiter
- .../index.php?title=Vorlage:Auftragsverarbeiter&action=edit

und z. B. an gewünschter Stelle
```
|-
| Status des AV
|{{#info:Status des AV}}
| [[Status des AV::{{{StatusAV|}}}]]
```
einfügst.

**Comment by jifflaender** [comment]
wie oben bereits beschrieben: **bearbeiten**
.../index.php?title=Vorlage:Auftragsverarbeiter&action=edit

oder
.../index.php/Vorlage:Auftragsverarbeiter und auf Stiftsymbol klicken.

**Comment by ZoXx** [comment]
Aber exakt das habe ich ja gemacht und bei StatusAV ist nichts eintragbar.

Vorlage:Auftragsverarbeiter
```
<noinclude>Vorlage für Auftragsverarbeiter
<pre>
{{Auftragsverarbeiter}}
</pre>
[[Kategorie:Vorlagen]]
</noinclude><includeonly>__NOTOC__
<div class="panel panel-default  mw-collapsible"><div class="panel-heading"><h3 class="panel-title ">Auftragsverarbeiter</h3></div>
<div class="panel-body mw-collapsible-content">
{| class="table-hover table-responsive table-condensed"  
|-
| [[Attribut:Organisation|Name]]
|{{#info:Name der Organisation}}
| [[Seitenname::{{FULLPAGENAME}}|{{PAGENAME}}]]
|-
| [[Attribut:Straße|Straße]]
|{{#info:Straße}}
| [[Straße::{{{Straße|}}}]]
|-
| [[Attribut:PLZ|Postleitzahl]]
|{{#info:Postleitzahl}}
| [[PLZ::{{{PLZ|}}}]]
|-
| [[Attribut:Ort|Ort]]
|{{#info:Ort}}
| [[Ort::{{{Ort|}}}]] 
|-
| [[Attribut:Website|Website]]
|{{#info:Website der Organisation.}}
| [[Website::{{{Website |}}}]]
|-
| Kontaktperson
|{{#info:Name von Kontaktpersonen des Aufrragsverarbeiters}}
|{{#arraymap:{{{Kontaktperson|}}}|,|@@@@|[[Kontaktperson::@@@@]]}}
|-
| Status des AV
|{{#info:Ist der AV vorhanden, angefragt oder nicht vorhanden?}}
| [[Status des AV::{{{StatusAV|}}}]]
|-
| Datum des AV
|{{#info:Datum, an dem der AV ausgestellt wurde.}}
| [[Datum des AV::{{{DatumAV|}}}]]
|-
| Aufgabe für
|{{#info:BenutzerInnen können Aufgaben zugewiesen werden, die in der Liste auf ihrer Benutzerseite angezeigt werden.}}
| {{#arraymap:{{{Aufgabe für|}}}|,|@@@@|{{#ifeq:{{#sub:@@@@|0|9}}|Benutzer:|[[Aufgabe für::@@@@|{{#sub:@@@@|9}}]]|[[Aufgabe für::Benutzer:@@@@|@@@@]]}}}}
|-
|[{{fullurl:{{FULLPAGENAME}}}}&action=history Letze Änderung] 
|
| {{REVISIONYEAR}}/{{REVISIONMONTH1}}/{{REVISIONDAY}} durch [[Benutzer:{{REVISIONUSER}}|{{REVISIONUSER}}]]
|}
{{#if: {{{Dokument|}}}|
<div class="panel panel-default  mw-collapsible mw-collapsed"><div class="panel-heading"><h3 class="panel-title ">Dokument: [[Media:{{{Dokument|}}}|{{{Dokument|}}}]]</h3></div>
<div class="panel-body mw-collapsible-content">[[Dokument::Datei:{{{Dokument|}}}|]]
[[:Datei:{{{Dokument|}}}|Details]]
{{#widget:PDF
 |url={{filepath: {{#replace:{{{Dokument|}}}|Datei:|}}}}
}}</div></div>
|
}}</div></div>
[[Kategorie:Auftragsverarbeiter]]{{#default_form:Auftragsverarbeiter}}
</includeonly>
```

**Comment by jifflaender** [comment]
Vorlagen zeigen die den Inhalt an. Wird ein Auftragsverarbeiter angezeigt, geschieht das mit der entsprechenden (Seiten-)Vorlage. Dort kann nichts eingetragen werden. Dafür ist das Formular zuständig (aus der Vorlagenansicht das Stiftsymbol anklicken)...

**Comment by ZoXx** [comment]
Wenn ich aus der Vorlagenansicht 
`/index.php?title=Vorlage:Auftragsverarbeiter&action=edit` anklicke:
```
<noinclude>Vorlage für Auftragsverarbeiter
<pre>
{{Auftragsverarbeiter}}
</pre>
[[Kategorie:Vorlagen]]
</noinclude><includeonly>__NOTOC__
<div class="panel panel-default  mw-collapsible"><div class="panel-heading"><h3 class="panel-title ">Auftragsverarbeiter</h3></div>
<div class="panel-body mw-collapsible-content">
{| class="table-hover table-responsive table-condensed"  
|-
| [[Attribut:Organisation|Name]]
|{{#info:Name der Organisation}}
| [[Seitenname::{{FULLPAGENAME}}|{{PAGENAME}}]]
|-
| [[Attribut:Straße|Straße]]
|{{#info:Straße}}
| [[Straße::{{{Straße|}}}]]
|-
| [[Attribut:PLZ|Postleitzahl]]
|{{#info:Postleitzahl}}
| [[PLZ::{{{PLZ|}}}]]
|-
| [[Attribut:Ort|Ort]]
|{{#info:Ort}}
| [[Ort::{{{Ort|}}}]] 
|-
| [[Attribut:Website|Website]]
|{{#info:Website der Organisation.}}
| [[Website::{{{Website |}}}]]
|-
| Kontaktperson
|{{#info:Name von Kontaktpersonen des Aufrragsverarbeiters}}
|{{#arraymap:{{{Kontaktperson|}}}|,|@@@@|[[Kontaktperson::@@@@]]}}
|-
| Status des AV
|{{#info:Ist der AV vorhanden, angefragt oder nicht vorhanden?}}
| [[Status des AV::{{{StatusAV|}}}]]
|-
| Datum des AV
|{{#info:Datum, an dem der AV ausgestellt wurde.}}
| [[Datum des AV::{{{DatumAV|}}}]]
|-
| Aufgabe für
|{{#info:BenutzerInnen können Aufgaben zugewiesen werden, die in der Liste auf ihrer Benutzerseite angezeigt werden.}}
| {{#arraymap:{{{Aufgabe für|}}}|,|@@@@|{{#ifeq:{{#sub:@@@@|0|9}}|Benutzer:|[[Aufgabe für::@@@@|{{#sub:@@@@|9}}]]|[[Aufgabe für::Benutzer:@@@@|@@@@]]}}}}
|-
|[{{fullurl:{{FULLPAGENAME}}}}&action=history Letze Änderung] 
|
| {{REVISIONYEAR}}/{{REVISIONMONTH1}}/{{REVISIONDAY}} durch [[Benutzer:{{REVISIONUSER}}|{{REVISIONUSER}}]]
|}
{{#if: {{{Dokument|}}}|
<div class="panel panel-default  mw-collapsible mw-collapsed"><div class="panel-heading"><h3 class="panel-title ">Dokument: [[Media:{{{Dokument|}}}|{{{Dokument|}}}]]</h3></div>
<div class="panel-body mw-collapsible-content">[[Dokument::Datei:{{{Dokument|}}}|]]
[[:Datei:{{{Dokument|}}}|Details]]
{{#widget:PDF
 |url={{filepath: {{#replace:{{{Dokument|}}}|Datei:|}}}}
}}</div></div>
|
}}</div></div>
[[Kategorie:Auftragsverarbeiter]]{{#default_form:Auftragsverarbeiter}}
</includeonly>
```

**Comment by jifflaender** [comment]
Der Auftragsverarbeiter wird angezeigt (z. B. Stammdaten -> Auftragsverarbeiter -> AV anklicken)
Für diese Anzeige ist die Vorlage:Auftragsverarbeiter zuständig. Hier kann nichts geändert bzw. eingetragen werden.
Soll der Auftragsverarbeiter bearbeitet werden, klickt man auf das Stiftsymbol und das Formular:Auftragsverarbeiter öffnet sich. Hier können am Auftragsverarbeiter dann Änderungen vorgenommen werden.

**Comment by ZoXx** [comment]
Ich glaube wir reden aneinander vorbei.

Wenn ich einen neuen Auftragsverarbeiter anlege, muss ich ja die Felder:
StatusAV und DatumAV auswählen. DatumAV ist auswählbar, wird dann jedoch hinterher rot angezeigt in der Übersicht. StatusAV ist ein leeres Dropdown.

**Comment by jifflaender** [comment]
noch einmal zusammengefasst (ich habe das in meiner Testumgebung mal nachgebaut):
im bearbeiteten Formular steht
```
|-
| Status AV:
|{{#info:Status AV}}
|{{{field|Status|input type=dropdown|class=form-control}}}
```
in der bearbeiteten Vorlage steht
```
|-
| Status des AV
|{{#info:Status des AV}}
| [[StatusAV::{{{Status|}}}]]
```
Das Attribut "StatusAV" sieht so aus:
```
* [[Erlaubt Wert::1 - vorhanden]]
* [[Erlaubt Wert::2 - nicht vorhanden]]
* [[Erlaubt Wert::3 - angefragt]]

[[Kategorie:Attribute]]
```

Das Ergebnis sieht so aus:
![StatusAV](https://user-images.githubusercontent.com/41866859/54187566-2d81f280-44ae-11e9-9880-e88d1cbb1762.png)

Bitte einmal Buchstqabe für Buchstabe so übernehmen und erst wenn es richtig angezeigt wird,  gewünschte Änderungen vornehmen. Dann weißt Du, woran es evtl. liegt...

**Comment by jifflaender** [comment]
und .../index.php/Attribut:StatusAV zeigt:
![StatusAV-2](https://user-images.githubusercontent.com/41866859/54188403-e98fed00-44af-11e9-9ef0-73ae42f5a6dc.png)

**Comment by jifflaender** [comment]
Ergänzung: da es das Attribut "Datum" bereits gibt, müsste es eigentlich nicht neu angelegt werden, sondern lediglich verwendet werden...

**Comment by ZoXx** [comment]
@jifflaender verstanden! Ich habe es so gemacht wie du es nun beschrieben hast und es funktioniert. Es lag daran, dass ich die "Anweisungen" noch nicht ganz verstanden hatte. Habe die nötigen Schritte mal notiert und dokumentiert und nun läuft es so! Vielen vielen Dank! Auch für die Geduld.
