### ISSUE TITLE
Sie haben keine verantworliche BenutzerInnen definiert!

### ISSUE THREAD

**Issue by ZoXx** [krabina/Datencockpit#45]
Wird in der Checkliste immer noch als offener Punkt gelistet, obwohl User angelegt sind. Ist hier der alte Bug doch noch vorhanden? Bei euch im Demo Portal ebenfalls:
http://www.datencockpit.at/Checkliste

**Comment by krabina** [comment]
Dem User muss die Funktion "Verantwortliche/r" zugeordnet werden, kann klappt es auch. 
http://www.datencockpit.at/index.php?title=Benutzer:Admin&curid=40&diff=3406&oldid=3280

**Comment by ZoXx** [comment]
Guten Morgen,
alles klar das macht Sinn. 

Stellt sich mir nur die Frage für was ist er denn dann Verantwortlicher?

**Comment by jifflaender** [comment]
Artikel 4 Ziffer 7 DSGVO

**Comment by ZoXx** [comment]
Alles klar, dann liege ich doch richtig! Danke! 👍
