### ISSUE TITLE
Neues Verfahren erscheint nicht in Auflistung

### ISSUE THREAD

**Issue by devaxel** [krabina/Datencockpit#46]
Wenn ich ein neues Verfahren hinzufüge, alle Angaben dazu mache und "Seite speichern" anklicke, wird erfolgreich gespeichert. Rufe ich dann den Menüpunkt Datenschutz--> Verfahren auf, wird es nicht aufgeführt, stattdessen steht dort "Sie haben noch keine....". 
Ist das ein Bug? Sollte es nicht in dieser Ansicht aufgeführt werden?

**Comment by jifflaender** [comment]
Hallo @devaxel,
ist die Übersichtsseite evtl. noch im Cache? Hast Du "Neu laden" ("..." links neben Suchfeld oben auf der Seite -> "Neu laden") mal ausprobiert?
Falls es das gewesen sein sollte: es gibt hier im Forum bereits einige Beiträge zum Umgang mit dem Caching...

**Comment by Zabien** [comment]
Da war jemand schon schneller. Genau, ist wohl eher eine Sache der Job Queue, in der die neuen Berechnungen noch hängen. Reines Browser-Refreshen oder Cache leeren hilft hier nicht, also die "Neu laden"-Funktion nutzen.

**Comment by devaxel** [comment]
Hallo @jifflaender, danke - "Neu laden" anklicken hat geholfen.
