### ISSUE TITLE
Datenbank besser entleeren

### ISSUE THREAD

**Issue by krabina** [krabina/Datencockpit#6]
In der nächsten Version sollte die Datenbank besser geleert werden. Das betrifft z. B. die Seite "Testorganisation". User klicken intuitiv aus "Bearbeiten" und ergänzen dann ihre Daten. Dies Seite heißt dann immer noch "Testorganisation". Diese müsste dann über den "Verschieben-Dialog" umbenannt werden.

Eleganter ist es, die Seite "Testorganisation" händisch zu löschen (bzw. in Zukunft eben gar nicht auszuliefern). Dann erscheint auf der Seite "Organisation" nämlich das Formular, mit dem man eine neue Organisationsseite anlegen kann.

Lasse das hier als Bug stehen, um das in Version 0.2 zu berücksichtigen.

Weitere unnötige Inhalte sind 
* User-Seiten inkl. User-Diskussions-Seiten, z. B: "Benutzer Diskussion:Admin"
* andere User in der DB als Admin

**Comment by maschinengeist** [comment]
Anbei ein Dump einer leeren Datenbank - dort habe ich versucht soviel als möglich zu entfernen - inkl. User, Kommentare, etc...

[datencockpit.clean.20181004.zip](https://github.com/krabina/Datencockpit/files/1899143/datencockpit.clean.20181004.zip)

**Comment by riess82** [comment]
In dieser leeren Datenbank hat der Admin scheinbar ein anderes Passwort. Das Passwort lässt sich aber über die changePassword.php ändern.

**Comment by maschinengeist** [comment]
Ja stimmt - mein Fehler - sorry :(

**Comment by krabina** [comment]
Erledigt in V 0.2: https://github.com/krabina/Datencockpit/blob/master/webserver/kdz_datencockpit.sql
