### ISSUE TITLE
Nicht benötigte Extensions entfernen

### ISSUE THREAD

**Issue by krabina** [krabina/Datencockpit#7]
ev. wäre anzudenken, nicht unbedingt benötigte Extensions zu entfernen, um alles übersichtlicher zu halten.

Das wären z. B.
* Semantic Compound Queries
* Semantic Drilldown
* Semantic Internal Objects
* External Data
* Piwik Integration

Sowie einige in MediwWiki mit ausgelieferte zu deaktivieren:
* CiteThisPage
* Nuke
* ImageMap
* Poem

**Comment by krabina** [comment]
sind in V 0.2 aus LocalSettings.php auskommentiert

**Comment by kghbln** [comment]
@krabina Was ist mit der Erweiterung "DeleteBatch". Für den Anfänger ggf. eher "scary"

**Comment by krabina** [comment]
Wird im Datencockpit nicht unbedingt benötigt. User, die es weghaben wollen, können es einfach in LocalSettings.php mit
`#wfLoadExtension( 'DeleteBatch' ); `
auskommentieren.

https://www.mediawiki.org/wiki/Extension:DeleteBatch könnte aber praktisch sein, wenn man z. B. draufkommt, dass man die Fragestellungen oder die DSG-Texte doch nicht drinnen habe möchte oder wenn man in ein paar Jahren der Nutzung Inhalte löschen möchte.

**Comment by kghbln** [comment]
Vielen Dank für die Rückmeldung. Bin im Bilde. An der Nützlichkeit hatte ich keinen Zweifel. :)
