### ISSUE TITLE
Installation auf einem Webserver

### ISSUE THREAD

**Issue by riess82** [krabina/Datencockpit#8]
Bei Installation auf einem Webserver musste ich die Berechtigungen für /images neu setzen und zusätzlich ImageMagick und php-imageick installieren.
Damit funktioniert nun das Logo der eigenen Organisation.

**Comment by krabina** [comment]
Ja, siehe z. B: 
https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki/de#Dateien_hochladen
und
https://www.mediawiki.org/wiki/Manual:Installation_requirements/de

**Comment by riess82** [comment]
Ja, aber dort unter optionale Abhängigkeiten gelistet. Durch die spezifische Verwendung im Datencockpit, sehe ich das als notwendig und nicht als optional. Durch den Thread hier aber vermutlich auch für die Zukunft ausreichend dokumentiert.
